[tool.poetry]
name = "web"
version = "0.1.0"
description = ""
authors = ["slavanr45 <slava.r45@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
gunicorn = "^21.2.0"
flask = "^2.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
